/**
 * Hub instrument list — display names, synthesis, sensors (paths stay stable).
 */
export const HUB_APPS = [
  {
    href: "apps/conductor/",
    title: "Conductor",
    section: "rhythm",
    synth: "Ensemble click",
    sensors: "Touch · shared URL",
  },
  {
    href: "apps/part/",
    title: "Seat Ticket",
    section: "rhythm",
    synth: "Routing only",
    sensors: "QR · touch",
  },
  {
    href: "apps/drumkit/",
    title: "Hand Drum Circle",
    section: "rhythm",
    synth: "Drum synthesis",
    sensors: "Touch",
  },
  {
    href: "apps/drum-sequencer/",
    title: "Step Lane",
    section: "rhythm",
    synth: "Step sequencer",
    sensors: "Touch",
  },
  {
    href: "apps/circular-drum/",
    title: "Orbit Groove",
    section: "rhythm",
    synth: "Ring sequencer",
    sensors: "Touch",
  },
  {
    href: "apps/firefly/",
    title: "Firefly Sync",
    section: "rhythm",
    synth: "Pulse click",
    sensors: "Mic · touch",
  },
  {
    href: "apps/delay-throw/",
    title: "Echo Toss",
    section: "rhythm",
    synth: "Delay feedback",
    sensors: "Touch · tilt",
  },
  {
    href: "apps/evo-drumkit/",
    title: "Groove Gene",
    section: "ai",
    synth: "Evolving drums",
    sensors: "Touch · mic",
  },
  {
    href: "apps/audience/",
    title: "Murmuration",
    section: "drones",
    synth: "Swarm tones",
    sensors: "Touch · motion",
  },
  {
    href: "apps/drone-choir/",
    title: "Held Voices",
    section: "drones",
    synth: "Detuned sines",
    sensors: "Touch",
  },
  {
    href: "apps/sound-saber/",
    title: "Sabre Pulse",
    section: "drones",
    synth: "Pulse · delay · ring",
    sensors: "Touch · motion",
  },
  {
    href: "apps/compass-wah/",
    title: "Motion Filter",
    section: "drones",
    synth: "5 filter modes",
    sensors: "Touch · motion · compass",
  },
  {
    href: "apps/harmonizer/",
    title: "Neighbourhood Chord",
    section: "drones",
    synth: "Chroma drones",
    sensors: "Mic · touch",
  },
  {
    href: "apps/piano/",
    title: "Glass Keys",
    section: "melody",
    synth: "Keyboard tones",
    sensors: "Touch",
  },
  {
    href: "apps/synth-pad/",
    title: "Wedge Lead",
    section: "melody",
    synth: "Subtractive pad",
    sensors: "Touch",
  },
  {
    href: "apps/mic-theremin/",
    title: "Humming Stone",
    section: "melody",
    synth: "Pitch-tracked sine",
    sensors: "Mic · touch",
  },
  {
    href: "apps/flute-blow/",
    title: "Breath Flute",
    section: "melody",
    synth: "Breath tone",
    sensors: "Mic · touch",
  },
  {
    href: "apps/light-theremin/",
    title: "Shadow Tone",
    section: "melody",
    synth: "Light theremin",
    sensors: "Light · touch",
  },
  {
    href: "apps/tilt-harp/",
    title: "Gravity Harp",
    section: "melody",
    synth: "Plucked harp",
    sensors: "Touch · tilt",
  },
  {
    href: "apps/bow-phone/",
    title: "Selfie Bow",
    section: "melody",
    synth: "Bowed string",
    sensors: "Touch · camera",
  },
  {
    href: "apps/fm-touch/",
    title: "FM Fingerpaint",
    section: "synthesis",
    synth: "2-op FM · finger or tilt",
    sensors: "Touch · tilt",
  },
  {
    href: "apps/fm-matrix/",
    title: "FM Patchbay",
    section: "synthesis",
    synth: "FM matrix",
    sensors: "Touch",
  },
  {
    href: "apps/ks-string/",
    title: "Resonant Wire",
    section: "synthesis",
    synth: "KS · stage or pocket",
    sensors: "Touch · tilt",
  },
  {
    href: "apps/additive-bells/",
    title: "Harmonic Bells",
    section: "synthesis",
    synth: "Additive partials",
    sensors: "Touch · motion",
  },
  {
    href: "apps/filter-ladder/",
    title: "Ladder Groan",
    section: "synthesis",
    synth: "Ladder lowpass",
    sensors: "Touch · tilt",
  },
  {
    href: "apps/ring-mod-gong/",
    title: "Bronze Clang",
    section: "synthesis",
    synth: "Ring modulation",
    sensors: "Touch",
  },
  {
    href: "apps/sampler/",
    title: "Field Catcher",
    section: "texture",
    synth: "Sample playback",
    sensors: "Mic · touch · tilt",
  },
  {
    href: "apps/granular-tilt/",
    title: "Dust Drift",
    section: "texture",
    synth: "Granular cloud",
    sensors: "Touch · tilt · mic",
  },
  {
    href: "apps/spectral-freeze/",
    title: "Prism Hold",
    section: "texture",
    synth: "FFT partials",
    sensors: "Mic · touch",
  },
  {
    href: "apps/wavetable-scan/",
    title: "Wave Rider",
    section: "texture",
    synth: "Wavetable morph",
    sensors: "Touch",
  },
  {
    href: "apps/video-sonifier/",
    title: "Motion Cam",
    section: "texture",
    synth: "Camera → sound",
    sensors: "Camera",
  },
  {
    href: "apps/hum-clap/",
    title: "Call & Clap",
    section: "ai",
    synth: "k-NN classifier",
    sensors: "Mic",
  },
  {
    href: "apps/train-shake/",
    title: "Gesture School",
    section: "ai",
    synth: "ML gesture map",
    sensors: "Motion",
  },
  {
    href: "apps/markov-melody/",
    title: "Chain Melody",
    section: "melody",
    synth: "2nd-order Markov",
    sensors: "Touch · keyboard",
  },
  {
    href: "apps/euclidean-rings/",
    title: "Pulse Lattice",
    section: "rhythm",
    synth: "Euclidean rings",
    sensors: "Touch",
  },
  {
    href: "apps/lsystem-groove/",
    title: "Fractal Lane",
    section: "rhythm",
    synth: "L-system rewrite",
    sensors: "Touch",
  },
  {
    href: "apps/chaos-attractor/",
    title: "Strange Attractor",
    section: "texture",
    synth: "Chaotic subtractive",
    sensors: "Touch · motion",
  },
  {
    href: "apps/bit-crush-pad/",
    title: "Arcade Static",
    section: "texture",
    synth: "Bit crush",
    sensors: "Touch · motion · network",
  },
  {
    href: "apps/feedback-matrix/",
    title: "Delay Maze",
    section: "texture",
    synth: "Feedback delays",
    sensors: "Touch · gyro",
  },
  {
    href: "apps/shepard-glide/",
    title: "Endless Rise",
    section: "drones",
    synth: "Shepard tone",
    sensors: "Touch · tilt",
  },
  { href: "apps/gravity-bounce/", title: "Drop Bell", section: "synthesis", synth: "KS impact", sensors: "Accel · touch" },
  { href: "apps/pocket-metronome/", title: "Pocket Pulse", section: "rhythm", synth: "Pulse + duck", sensors: "Accel · touch" },
  { href: "apps/tilt-doppler/", title: "Doppler Tilt", section: "melody", synth: "Pitch glide", sensors: "Tilt · touch" },
  { href: "apps/room-reverb-send/", title: "Room Wash", section: "texture", synth: "Convolver wet", sensors: "Mic · touch" },
  { href: "apps/whisper-gate/", title: "Soft Vowel", section: "texture", synth: "Formant noise", sensors: "Mic · touch" },
  { href: "apps/clap-architect/", title: "Clap Grid", section: "rhythm", synth: "Learned kit", sensors: "Mic · touch" },
  { href: "apps/pitch-hive/", title: "Hum Hive", section: "drones", synth: "Additive chord", sensors: "Mic · touch" },
  { href: "apps/feedback-flute/", title: "Whistle Loop", section: "melody", synth: "Resonant bandpass", sensors: "Mic · touch" },
  { href: "apps/shadow-sequencer/", title: "Shadow Steps", section: "rhythm", synth: "8-step mask", sensors: "Camera · touch" },
  { href: "apps/torch-pulse/", title: "Flash Beat", section: "rhythm", synth: "Click + flash", sensors: "Camera · touch" },
  { href: "apps/pinch-bass/", title: "Pinch Sub", section: "synthesis", synth: "Subtractive bass", sensors: "Pinch · touch" },
  { href: "apps/edge-strum/", title: "Rim Pluck", section: "synthesis", synth: "KS harmonics", sensors: "Touch position" },
  { href: "apps/haptic-click/", title: "Vibe Lane", section: "rhythm", synth: "Sequencer + vibe", sensors: "Touch · vibrate" },
  { href: "apps/battery-drone/", title: "Power Thin", section: "drones", synth: "Detune drift", sensors: "Battery · touch" },
  { href: "apps/altitude-wind/", title: "Baro Wind", section: "drones", synth: "Filtered noise", sensors: "Barometer · touch" },
  { href: "apps/geo-drone/", title: "Walk Pan", section: "drones", synth: "Stereo delay", sensors: "GPS · touch" },
  { href: "apps/hard-sync-lead/", title: "Sync Scream", section: "synthesis", synth: "Hard sync lead", sensors: "Touch" },
  { href: "apps/am-radio/", title: "AM Dial", section: "synthesis", synth: "AM sidebands", sensors: "Mic · touch" },
  { href: "apps/phase-distortion/", title: "PD Lead", section: "synthesis", synth: "Phase distortion", sensors: "Touch" },
  { href: "apps/supersaw-stack/", title: "Blade Chorus", section: "synthesis", synth: "Saws or spin timbre", sensors: "Gyro · touch" },
  { href: "apps/pwm-bass/", title: "Pulse Bass", section: "synthesis", synth: "Variable pulse", sensors: "Tilt · touch" },
  { href: "apps/dual-ks-harp/", title: "Twin Wire", section: "synthesis", synth: "Dual KS", sensors: "Multi-touch" },
  { href: "apps/bowed-waveguide/", title: "Drag Bow", section: "melody", synth: "Continuous KS", sensors: "Touch drag" },
  { href: "apps/pluck-bowl/", title: "Bowl Splash", section: "synthesis", synth: "Resonant burst", sensors: "Touch position" },
  { href: "apps/wind-bottle/", title: "Bottle Breath", section: "texture", synth: "Noise resonator", sensors: "Tilt · touch" },
  { href: "apps/grain-rain/", title: "Shake Dust", section: "texture", synth: "Grain shower", sensors: "Accel · touch" },
  { href: "apps/scrub-tape/", title: "Tape Scrub", section: "texture", synth: "Buffer scrub", sensors: "Touch drag" },
  { href: "apps/vocoder-choir/", title: "Robot Hall", section: "texture", synth: "Band vocoder", sensors: "Mic · tilt" },
  { href: "apps/ir-cathedral/", title: "Space Convolve", section: "texture", synth: "IR convolution", sensors: "Tilt · touch" },
  { href: "apps/one-shot-orchestra/", title: "Zone Hits", section: "rhythm", synth: "Multi-zone", sensors: "Touch zones" },
  { href: "apps/live-loop-slicer/", title: "Slice Bar", section: "rhythm", synth: "Loop slices", sensors: "Tilt · touch" },
  { href: "apps/gesture-regression/", title: "Tilt Learn", section: "ai", synth: "ML → filter", sensors: "Motion · touch" },
  {
    href: "apps/swarm-bloom/",
    title: "Swarm Bloom",
    section: "drones",
    synth: "Evo drones + rhythm",
    sensors: "Mic · ensemble",
  },
];

/** @param {string} href e.g. "apps/piano/" */
export function catalogEntryForHref(href) {
  return HUB_APPS.find((a) => a.href === href);
}

/** Folder slug from href: "piano" */
export function slugFromHref(href) {
  const m = href.match(/apps\/([^/]+)\//);
  return m ? m[1] : "";
}
